/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 MUS.glb -T 
Files: MUS.glb [5.33MB] > C:\Users\VR-MSc\Desktop\3D Portfolio Fixed\public\models\MUS-transformed.glb [985.02KB] (82%)
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";


export function MUS(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/models/MUS-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
   
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Fcar_ford_mustanggt_2014_Mesh_lod0M_Badges_High_Fphong13SG1_0.geometry} material={materials.Fphong13SG1} scale={0.549} />
      <mesh geometry={nodes.Fcar_ford_mustanggt_2014_Mesh_lod0M_BrakeDisc_High_Fphong15SG.geometry} material={materials.Fphong15SG1} scale={0.549} />
      <mesh geometry={nodes.Fcar_ford_mustanggt_2014_Mesh_lod0M_Caliper_High_Fphong14SG1_.geometry} material={materials.Fphong14SG1} scale={0.549} />
      <mesh geometry={nodes.Fcar_ford_mustanggt_2014_Mesh_lod0M_Chassis_High_Fphong10SG1_.geometry} material={materials.PaletteMaterial001} scale={0.549} />
      <mesh geometry={nodes.Fcar_ford_mustanggt_2014_Mesh_lod0M_Glass_Window_High_Fphong2.geometry} material={materials.PaletteMaterial002} scale={0.549} />
      <mesh geometry={nodes.Fcar_ford_mustanggt_2014_Mesh_lod0M_Glass_Window_High_Fphong3.geometry} material={materials.PaletteMaterial003} scale={0.549} />
      <mesh geometry={nodes.Fcar_ford_mustanggt_2014_Mesh_lod0M_Glass_WindowSurround_High_.geometry} material={materials.PaletteMaterial004} scale={0.549} />
      <mesh geometry={nodes.Fcar_ford_mustanggt_2014_Mesh_lod0M_GrilleA_High_Fphong11SG1_.geometry} material={materials.Fphong11SG1} scale={0.549} />
      <mesh geometry={nodes.Fcar_ford_mustanggt_2014_Mesh_lod0M_GrilleB_High_Fphong12SG1_.geometry} material={materials.Fphong12SG1} scale={0.549} />
      <mesh geometry={nodes.Fcar_ford_mustanggt_2014_Mesh_lod0M_Internal_Engine_High_Fpho.geometry} material={materials.Fphong5SG1} scale={0.549} />
      <mesh geometry={nodes.Fcar_ford_mustanggt_2014_Mesh_lod0M_LicensePlate_High_Fphong7.geometry} material={materials.PaletteMaterial005} scale={0.549} />
      <mesh geometry={nodes.Fcar_ford_mustanggt_2014_Mesh_lod0M_LightCluster_High_Fphong8.geometry} material={materials.Fphong8SG1} scale={0.549} />
      <mesh geometry={nodes.Fcar_ford_mustanggt_2014_Mesh_lod0M_LightRefracted_High_Fphon.geometry} material={materials.Fphong9SG1} scale={0.549} />
      <mesh geometry={nodes.Fcar_ford_mustanggt_2014_Mesh_lod0M_Paint_Metal_AltColor_High_.geometry} material={materials.Fphong4SG1} scale={0.549} />
      <mesh geometry={nodes.Fcar_ford_mustanggt_2014_Mesh_lod0M_PaintNormalMap_High_Finit.geometry} material={materials.PaletteMaterial006} scale={0.549} />
      <mesh geometry={nodes.Fcar_ford_mustanggt_2014_Mesh_lod0M_Rim_High_Fphong16SG1_0.geometry} material={materials.Fphong16SG1} scale={0.549} />
      <mesh geometry={nodes.FM_Tire_Highcar_ford_mustanggt_2014_Mesh_lod0_Fphong1SG1_0.geometry} material={materials.Fphong1SG1} scale={0.549} />
      
    </group>
  )
}

useGLTF.preload('/MUS-transformed.glb')
